bin/config.ts

chore: lower rcu

---

bin/stacks/api-stack.ts
lib/handlers/get-docs/swagger-ui.ts
swagger.json

- Remove `isFeeOutput` from swagger field
- Change docs json endpoint

fix: remove isFeeOutput field from swagger

---

bin/stacks/api-stack.ts
bin/stacks/lambda-stack.ts
lib/handlers/base/dynamo-stream-handler.ts
lib/handlers/order-notification/handler.ts
lib/handlers/order-notification/injector.ts
test/handlers/order-notification.test.ts

- Add order notification metrics 
- Add order notification alarms on metrics

feat: add order notifications metrics

---

lib/handlers/check-order-status/handler.ts
package.json
yarn.lock

so that in the case of ExactIn orders we know the actual settled amount

feat: log token transferred to swapper (tokenIn) and amount

---

bin/stacks/lambda-stack.ts

Very similar to https://github.com/Uniswap/uniswapx-parameterization-api/pull/195

chore: add static outbound IP for order notification lambda.

---

lib/handlers/check-order-status/handler.ts

so that we can delete old entries from redshift

chore: add logTime to fill logs

---

bin/stacks/cron-stack.ts
bin/stacks/lambda-stack.ts
lib/crons/gs-reaper.ts
lib/repositories/base.ts
lib/repositories/orders-repository.ts
lib/util/constants.ts
test/crons/gs-reaper.test.ts
test/handlers/get-orders.test.ts
test/repositories/dynamo-repository.test.ts

Completes [[GS] Reaper job](https://github.com/orgs/Uniswap/projects/22/views/28?pane=issue&itemId=34655244)
Query and deletes all open orders for which deadline is more than an hour in the past
Also tested in my dev account

feat: add gs reaper cron job

---

lib/entities/Order.ts
lib/handlers/get-orders/schema/index.ts
lib/handlers/post-order/handler.ts
lib/util/order-validator.ts
test/handlers/check-order-status.test.ts

Only log user output (defined by largest of outputs, assuming same token)

fix: posted order log

---

lib/util/order-validator.ts
test/util/order-validator.test.ts

limit orders for hackathon :shrug:
Consider removing maximum in the future

feat: raise max deadline to one day

---

swagger.json

verified swagger endpoint shows up and generates a valid curl request

update swagger with limit orders get request

---

lib/compute/on-chain-status-checker.ts

reduce recheck delay

---

lib/handlers/shared/sfn.ts

order hash is 66 characters and max is 82

update big number

---

bin/definitions/order-tracking-sfn.json
lib/handlers/check-order-status/handler.ts
lib/handlers/check-order-status/service.ts

pass in calculate retry wait seconds

Update calculate retry wait seconds

---

lib/Metrics.ts
lib/handlers/check-order-status/handler.ts
lib/handlers/check-order-status/service.ts

adds metrics to 
- load from dynamo
- getFillEvents
- getCurrentBlock
- validateOrder

add metrics in checkOrderStatusHandler code path

---

lib/handlers/post-order/handler.ts

add orderType to log for data analytics

adds orderType to OrderPosted event

---

bin/stacks/lambda-stack.ts

need to track postLimitOrder handler log group to enable the subscription filter

update subscription filter for postLimitOrders

---

lib/Logging.ts
lib/handlers/post-order/handler.ts
lib/services/UniswapXOrderService.ts
lib/services/analytics-service.ts
test/unit/services/analytics-service.test.ts

adds analytics service and switches the logger to powertools. test in beta to ensure logs flow to s3

add AnalyticsService

---

lib/handlers/check-order-status/handler.ts
lib/handlers/check-order-status/service.ts

fillEvent check is taking 10-20s so push it down to where it's needed

refactor fillevent check

---

bin/stacks/step-function-stack.ts
lib/handlers/check-order-status/handler.ts
lib/handlers/check-order-status/service.ts
lib/handlers/check-order-status/util.ts
lib/services/analytics-service.ts
test/e2e/order.test.ts
test/integ/handlers/check-order-status-service.test.ts
test/unit/services/analytics-service.test.ts
test/unit/services/check-order-status/util.test.ts

add cancelled and insufficient-funds logs for analytics

Add analytics

---

test/integ/handlers/check-order-status-service.test.ts
test/unit/handlers/post-limit-order.test.ts
test/unit/handlers/post-order.test.ts

fixes build errors from ts in tests. Previously this file was ts-ignore'd

fix ts errors in test

---

lib/util/order-validator.ts
test/unit/util/order-validator.test.ts

fix Deadline Validity period error message to reflect actual deadline

Deadline validity period error

---

lib/errors/InvalidTokenInAddress.ts
lib/handlers/base/ErrorCode.ts
lib/handlers/post-order/handler.ts
lib/services/UniswapXOrderService.ts
test/unit/handlers/post-order.test.ts

disallow address(0) as input token

feat: validate input token

---

package.json
yarn.lock

bump uniswapx-sdk to 2.0.1-alpha.0

bump uniswapx-sdk to 2.0.1-alpha.0

---

bin/stacks/step-function-stack.ts

this breaks redshifts status column varchar(9)

remove insufficient-funds from filled_event subscription

---

test/e2e/order.test.ts

currently they are submitting limit order input
next steps:
Add validations to limit endpoints to disable dutch orders
add validation to dutch endpoint to disable limit orders

make tests submit dutch orders

---

lib/services/UniswapXOrderService.ts
test/unit/services/UniswapXOrderService.test.ts

some orders in the db have type DUTCH_LIMIT

allow dutch_limit type

---

lib/handlers/get-orders/schema/GetOrderTypeQueryParamEnum.ts
lib/handlers/get-orders/schema/index.ts
lib/repositories/IndexMappers/OffchainOrderIndexMapper.ts
lib/repositories/base.ts
lib/repositories/generic-orders-repository.ts
lib/services/OrderDispatcher.ts
lib/services/UniswapXOrderService.ts
test/integ/repositories/dynamo-repository.test.ts
test/unit/services/OrderDispatcher.test.ts
test/unit/services/UniswapXOrderService.test.ts

adds filtering at the db level for orderType

add filters at db level

---

test/e2e/order.test.ts

disables all e2e tests that query goerli. Infura is returning noNetwork error

disable goerli tests

---

bin/stacks/lambda-stack.ts

adds env vars to the get orders lambdas

make env vars available in get path

---

lib/handlers/get-orders/schema/GetDutchV2OrderResponse.ts
lib/models/DutchV2Order.ts

add txHash to Dutch_V2 get response

add txHash to Dutch_V2 get response

---

bin/app.ts
lib/util/OffChainUniswapXOrderValidator.ts
test/e2e/order.test.ts

Adding an E2E test to ensure the services are working together before rolling out to production.
To make this test reliable I:
- Force open orders (don't need to worry about empty quotes)
- Decrease the amount prior to order so that the order is valid but wouldn't be filled
Before merging we need to add the following environment variables to Beta secrets
```
URA_SERVICE_URL="https://..."
GPA_SERVICE_URL="https://..."
COSIGNER_ADDRESS="..."
```

Add E2E test for pipeline check in beta

---

bin/stacks/dashboard-stack.ts
lib/handlers/check-order-status/fill-event-logger.ts
lib/services/analytics-service.ts

This will help us monitor for fading by filler

Add exclusive filler to analytic logs

---

.github/workflows/CI.yml
README.md
bin/app.ts
bin/stacks/step-function-stack.ts
lib/util/OffChainUniswapXOrderValidator.ts
lib/util/field-validator.ts
test/unit/util/field-validator.test.ts
test/unit/util/order-validator.test.ts

reads labs' cosigner addresses from AWS and checks if posted order contains the correct addr

feat: offchain validator checks labs cosigner addr

---

lib/handlers/post-limit-order/injector.ts
lib/handlers/post-order/handler.ts
lib/handlers/post-order/injector.ts

post-order lambda failing to deploy for unknown reasons. Reverting the recent changes to try to unblock the pipeline

fix: revert post-order handlers

---

bin/stacks/lambda-stack.ts

just trying to go back to the last successful state

fix: revert base addition

---

bin/stacks/lambda-stack.ts
package.json
yarn.lock

removing @uniswap/signer package to try to unblock pipeline

fix: remove signer

---

bin/stacks/api-stack.ts
bin/stacks/lambda-stack.ts
package.json
yarn.lock

trying to recover the beta stage from a weird and broken state 
- disabled beta to prod ✅

[TO-BE-REVERTED]fix: remove postOrder lambda reference

---

.github/workflows/CI.yml
lib/handlers/constants.ts
lib/handlers/get-orders/index.ts
lib/handlers/post-limit-order/index.ts
lib/handlers/post-order/PostOrderBodyParser.ts
lib/handlers/post-order/index.ts
lib/handlers/post-order/schema/index.ts
lib/handlers/shared/index.ts
lib/models/PriorityOrder.ts
lib/services/UniswapXOrderService.ts
test/factories/SDKPriorityOrderFactory.ts
test/unit/fixtures.ts
test/unit/handlers/post-order/post-order.test.ts
test/unit/services/UniswapXOrderService.test.ts

set `auctionTargetBlock` to current block + 1

chore: priority cosigner override

---

bin/stacks/api-stack.ts
bin/stacks/lambda-stack.ts

Reverts Uniswap/uniswapx-service#471

Revert "[TO-BE-REVERTED]fix: remove lambdas causing trouble"

---

bin/app.ts
lib/handlers/post-limit-order/injector.ts
lib/handlers/post-order/handler.ts
lib/handlers/post-order/injector.ts
lib/handlers/shared/post.ts
package.json
yarn.lock

Reverts Uniswap/uniswapx-service#473
also bumps uniswapx-sdk version to beta.10

Revert "fix: remove kmsClient at lambda initialization"

---

lib/services/UniswapXOrderService.ts
package.json
yarn.lock

- log cosigned priority order
- bump sdk

chore: log cosigner order; bump sdk

---

bin/stacks/lambda-stack.ts

we changed rpc secrets, so need to trigger a response to pick up the new values

fix: bump lambda version 

---

.github/workflows/CI.yml

Pins the sha hash for an action

fix(infra): pin sha hash

---

lib/entities/Order.ts
lib/handlers/get-unimind/schema/index.ts
lib/models/PriorityOrder.ts
lib/repositories/quote-metadata-repository.ts
lib/services/analytics-service.ts
test/unit/handlers/get-unimind/get-unimind.test.ts
test/unit/handlers/post-order/post-order.test.ts
test/unit/repositories/quote-metadata-repository.test.ts

Reverts Uniswap/uniswapx-service#520

Revert "feat, test: store and log classic blockNumber"

---

lib/handlers/check-order-status/fill-event-logger.ts
test/unit/handlers/fill-event-logger.test.ts

If there are multiple settled amounts, we should only log the largest of the original output token.

Fix logging of settled amounts

---

bin/stacks/step-function-stack.ts

It's currently hitting the 5 min timeout.

Increase reaper run timeout to 15 min

---

bin/stacks/api-stack.ts

Adding API keys for the following endpoints:
- GET /unimind
- POST /orders
- POST /limit-orders
All are currently disabled. Will enable them once we have all callers integrated with new keys (Trading API, URA, CLIs, and E2E tests)

Add disabled API keys

---

lib/crons/unimind-algorithm.ts
lib/unimind/priceImpactStrategy.ts

The gradient sometimes returns an undefined value. Add logging for intermediate calculations

feat: PriceImpact Algorithm gradient logging

---

lib/handlers/constants.ts
lib/models/PriorityOrder.ts
test/unit/handlers/post-order/post-order.test.ts

Increase Unichain target block delta to handle measured latency

Increase Unichain target block buffer

---

bin/stacks/lambda-stack.ts
lib/crons/gs-reaper.ts
lib/handlers/EventWatcherMap.ts
lib/handlers/check-order-status/index.ts
lib/handlers/check-order-status/injector.ts
lib/handlers/check-order-status/util.ts
lib/handlers/post-limit-order/index.ts
lib/handlers/post-order/index.ts
lib/util/constants.ts
test/e2e/order.test.ts
test/unit/handlers/gs-reaper/gs-reaper.test.ts

Set header for uniRPC

---

bin/stacks/lambda-stack.ts

bump version to pick up secret update

bump version

---

lib/crons/gs-reaper.ts

The job runs out of memory when processing a block range with many fill events. It seems that the large memory consumption because we're making many network requests in parallel. This change limits it to processing one fill event at a time. 
I also do some refactoring to make the function more legible.

fix(reaper): Process fillEvents serially

---

lib/config/unimind-list.ts
lib/handlers/get-unimind/handler.ts

We're seeing low fill rate on Arbitrum after expanding to a larger list of tokens.

Limit Unimind token set

---

bin/app.ts
bin/constants.ts
bin/stacks/cron-stack.ts
bin/stacks/lambda-stack.ts
bin/stacks/step-function-stack.ts
lib/services/analytics-service.ts
lib/util/analytics-events.ts

Log subscription filters pointing to destination ARNs from newly set up Firehose & S3 in GPA

feat: add subscription filters for Unimind firehose streams

---

bin/stacks/cron-stack.ts
bin/stacks/lambda-stack.ts

Merge after updating AWS Secrets

fix: remove role arns for Unimind subscription filters
