Uniswap/uniswapx-service

- test/integ/order.test.ts
this should prevent our broadcaster from picking up the orders submitted by our integ tests on goerli
> fix: make filler exclusive filler in integ tests 

- lib/handlers/post-order/handler.ts
archivedOrders table store checksummed filler address so we should do the same for postedOrders otherwise SQL string equality comparison would fail
> fix: checksum filler address in post-order log

- lib/handlers/check-order-status/handler.ts
- lib/util/constants.ts
- test/fixtures.ts
- test/handlers/check-order-status.test.ts
- test/handlers/post-order.test.ts
We are currently logging token transfers for the input on EXACT_OUT and ETH out orders. This fix logging for both cases.
Tested locally using local gouda service + bot for filling.
- exact out
- exact out ETH out
- exact in ETH out
- exact in
> fix: EXACT_OUT archive orders logging

- lib/entities/Order.ts
- lib/handlers/check-order-status/handler.ts
- test/handlers/check-order-status.test.ts
Right now for each fill with two outputs (user amount & fee), we log two events. We don't need the fee one since we have a completely separate source of truth for fees
> fix: only log user settled amounts

- bin/app.ts
Remove provisioned capacity for DynamoDB. We should switch to the auto scaling and PAY_PER_REQUEST set up. Our usage is so low I don't think it make sense to provision this. All of the usage charts for indexes look like the below chart.
> chore: remove provisioned db capacity

- jest.config.js
- package.json
- test/handlers/post-order.test.ts
- test/repositories/dynamo-repository.test.ts
- yarn.lock
Saw the backend team started using speedy web compiler and tested it out for UniswapX service. Works well!
ts-jest has a 6 - 12 second lag when compiling. This compilation lag gets extra bad if you run jest in watch mode. Instead, we can use [swc](https://swc.rs/docs/usage/jest#usage) as a drop-in replacement to reduce the lag to one second.
> chore: add speedy jest compilation

- lib/handlers/check-order-status/handler.ts
- lib/handlers/check-order-status/injector.ts
- test/handlers/check-order-status.test.ts
Avoids updating orders that have had no status updates.
These updates - which were occurring with every check on the order status - only served to re-trigger downstream dynamodb stream events, which was causing multiple webhooks to be sent for the same open orders.
> fix: do not update orders with no status change

- lib/providers/json-webhook-provider.ts
- lib/providers/types.ts
- test/providers/s3-webhook-provider.test.ts
Adds a glob to the webhook definition, to allow the JSON WebhookDefinition to include a catch-all that is sent every order and order update.
> feat: add glob to webhook definition

- lib/handlers/get-nonce/handler.ts
- test/handlers/get-nonce.test.ts
Orders are sanitized to have lowercased addresses before pumping into
the DB. This means all `offerers` in the nonce db also have lowercased
addresses. However, the getNonce query does not do sanitization, so if
any integrator requests eip-55 cased nonces, it will not find results in
the db. This commit sanitizes
However, we should hold out for the frontend to make a fix incrementing
the nonce. It's currently relying on nonce randomness to get new nonces
> fix: lowercase getNonce address

- bin/stacks/api-stack.ts
- bin/stacks/lambda-stack.ts
- lib/handlers/get-limit-orders/injector.ts
- lib/handlers/get-orders/injector.ts
- lib/handlers/index.ts
- lib/handlers/shared/get.ts
- package.json
adds GET /prod/limit/orders
curl --location '<baseUrl>/prod/limit/orders?orderStatus=open'
response:
```json
{
"orders": [
{
"outputs": [
{
"recipient": "0x5d5577a33abbbae5e7235d2d080caff47e94b7d0",
"startAmount": "37563544125610598",
"endAmount": "23722713488525370",
"token": "0x0000000000000000000000000000000000000000"
}
],
"encodedOrder": "0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000065bbc3650000000000000000000000000000000000000000000000000000000065bbc41900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000 …
```
> Add limit get

- lib/compute/on-chain-status-checker.ts
- lib/handlers/check-order-status/service.ts
- lib/handlers/post-limit-order/injector.ts
- lib/handlers/post-order/handler.ts
- lib/handlers/post-order/injector.ts
- test/unit/handlers/post-limit-order.test.ts
- test/unit/handlers/post-order.test.ts
Step functions were still being created for limit orders. They fail immediately due to being configured to check the dutch order table.
This disables the step function invocation for order types other than dutch orders.
Manual Tests:
Dutch order posts created a step function
Limit order posts did not create a step function
> Stop Limit orders from triggering step function

- lib/handlers/post-limit-order/index.ts
- test/e2e/order.test.ts
this was accidentally set to one day during some refactoring
Skipping e2e tests for this as they are failing because the goerli tests are taking too long/fee incorrectly set
> set limit order validation to one year

- test/e2e/order.test.ts
remove e2e tests that rely on goerli testnet until we can migrate to a new testnet
1. change RPC_5
2. Deploy contracts--may include uni token/dependent contracts
4. fund wallets(alice,filler)
> goerli is dead.

- test/e2e/order.test.ts
due to how we update the expiration, it might not be updated to expired within 1 second, so bumping the wait time by 20 seconds
> bump time to check expiration in e2e tests

- lib/util/chain.ts
- test/integ/handlers/check-order-status.test.ts
- test/unit/handlers/get-nonce.test.ts
- test/unit/handlers/get-orders.test.ts
- test/unit/handlers/post-order/post-limit-order.test.ts
- test/unit/handlers/post-order/post-order.test.ts
- test/unit/util/field-validator.test.ts
- yarn.lock
add this back so the e2e tests give some coverage.
need to either fund
/// Addresses on goerli:
///   alice address: 0xE001E6F6879c07b9Ac24291A490F2795106D348C
///   filler address: 0x8943EA25bBfe135450315ab8678f2F79559F4630 (also needs to have at least 0.1 ETH)
on sepolia or create new alice/filler addresses and fund them on sepolia
also need to update
export const WETH_GOERLI = '0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6'
export const UNI_GOERLI = '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984'
for sepolia
Test Suites: 1 skipped, 1 passed, 1 of 2 total
Tests:       5 skipped, 18 passed, 23 total
Snapshots:   0 total
Time:        232.093 s
Ran all test suites matching /test\/e2e\//i.
> add goerli back for e2e tests

- lib/handlers/get-orders/schema/GetDutchV2OrderResponse.ts
- lib/handlers/get-orders/schema/GetOrdersResponse.ts
- lib/models/DutchV2Order.ts
- lib/services/UniswapXOrderService.ts
completes [PROTO-255](https://linear.app/uniswap/issue/PROTO-255/orderservice-nonce-not-part-of-get-orders-response)
verified working locally
> feat: add nonce to GET /orders response for both v1 and v2 orders

- bin/stacks/step-function-stack.ts
Useful for Xv2 Mainnet and Arbitrum rollouts.
- Sev2 alarm if expired/filled > 20%
- Sev3 alarm if expired/filled > 5%
> Add alarms for order expiry

- bin/stacks/dashboard-stack.ts
- bin/stacks/step-function-stack.ts
- lib/handlers/check-order-status/fill-event-logger.ts
The following two charts in the Order Service dashboard are not useful:
- **Order Percent Decay Until Fill by Chain**: I've found that aggregating using an `avg` will give us real-time data while the P99 and P50 are very delayed and sparse. To fix this, I'm keeping the P99 and P50 while also adding the `avg` to the graph.
- **Blocks Until Fill by Chain**: The spikes of 20M make the chart unreadable. The problem is that when the `startingBlockNumber` is not present, it defaults to 0, leading the `BlocksUntilFill` to just be the current block height. The fix is to remove any case where `startingBlockNumber` is 0.
Also fix the `dimensionsMap` of the new expiry alert.
> Fix charts and alerts

- lib/handlers/get-orders/schema/GetDutchV2OrderResponse.ts
- lib/models/DutchV2Order.ts
- test/unit/models/DutchV2Order.test.ts
there is a bug in graphql for Dutch_V2 orders caused by missing createdAt date
> DAT-480 add createdAt to get response for Dutch_V2 objects

- bin/stacks/api-stack.ts
- bin/stacks/lambda-stack.ts
same `Resource handler returned message: "Provisioned Concurrency configuration failed to be applied. Reason: FAILED" (RequestToken: 9aea2c7d-1c2d-d851-2af7-264d24939869, HandlerErrorCode: NotStabilized)` error when trying to bump the x-sdk; was solved by https://github.com/Uniswap/uniswapx-service/pull/463
> [TO-BE-REVERTED]fix: remove lambdas causing trouble

- bin/app.ts
- lib/handlers/post-limit-order/injector.ts
- lib/handlers/post-order/handler.ts
- lib/handlers/post-order/injector.ts
- lib/handlers/shared/post.ts
We are stuck at `Resource handler returned message: "Provisioned Concurrency configuration failed to be applied. Reason: FAILED" (RequestToken: 9aea2c7d-1c2d-d851-2af7-264d24939869, HandlerErrorCode: NotStabilized)` error on deployments. One theory is that we are initializing too many things at lambda initialization and that somehow caused the `NotStabilized` error. This PR stops KmsClient initialization since we re-create it at every request anyways.
> fix: remove kmsClient at lambda initialization

- package.json
- yarn.lock
latest version of x sdk adds priorityOrderReactor-specific errors
> chore: bump x sdk to latest beta

- lib/handlers/check-order-status/index.ts
- lib/handlers/check-order-status/util.ts
It's used [here](https://github.com/Uniswap/uniswapx-service/blob/56b00d92d9d576055fe5723a86dfaaef8d00ff75/lib/handlers/check-order-status/index.ts#L58C7-L58C37) to determine retry wait secs.
> Add Arbitrum time for polling

- lib/util/field-validator.ts
- test/unit/handlers/post-order/post-limit-order.test.ts
- test/unit/handlers/post-order/post-order.test.ts
- test/unit/util/field-validator.test.ts
DutchV3 orders are a bit larger and are hitting the 3k char limit.
> Bump up encoded order length limit to 4k for DutchV3

- package.json
- yarn.lock
Recently updated the SDK cosigner digest to align with Dutch V3 contracts on replay protection
> feat: bump SDK for new cosigner digest

- lib/repositories/dutch-orders-repository.ts
- test/integ/repositories/dynamo-repository.test.ts
When inserting an order to the db, we get a `Field 'startingBaseFee' does not have a mapping or alias` error
> feat: add startingBaseFee to dynamoDB

- lib/handlers/check-order-status/fill-event-logger.ts
- lib/handlers/check-order-status/service.ts
In practice, there seem to be a tiny chance that the eth_getLogs call fail to get fill events for UniX orders. I suspect that this is due to certain blocks are not actually checked for some reason. An easy fix here is to pad the `startBlock` by a number of blocks, so that we are certain every block is checked from when the step function execution kicks off.
Also added a try-catch to fallback to still updating order status even when the `Promise.all(..)` call to get the specific fill tx fails.
> chore: overlap fill block check

- bin/stacks/dashboard-stack.ts
- bin/stacks/lambda-stack.ts
- lib/handlers/order-notification/handler.ts
The previous changes didn't improve the order notification staleness. The problem may be upstream so I'd like to see the time difference between the current time and the record's `ApproximateCreationDateTime` (when it's inserted into dynamo).
I also revert the `batchSize` to 1 since that increase didn't help us.
> Track record staleness

- bin/definitions/order-tracking-sfn.json
- bin/stacks/step-function-stack.ts
- lib/handlers/check-order-status/handler.ts
- lib/handlers/shared/sfn.ts
- lib/services/UniswapXOrderService.ts
- test/unit/handlers/post-order/post-limit-order.test.ts
- test/unit/services/UniswapXOrderService.test.ts
- test/unit/util/order-validator.test.ts
- maxAttempts 4 -> 100
- instead of postfixing orderHash with a random string, we postfix with retry # instead which should step function executions easier to track
> fix(order-tracking): sfn max attemmpts increase; sfn execution arn naming tweak

- bin/stacks/dashboard-stack.ts
- lib/entities/Order.ts
- lib/handlers/check-order-status/service.ts
- lib/handlers/get-orders/schema/GetDutchV3OrderResponse.ts
- lib/handlers/post-order/PostOrderBodyParser.ts
- lib/models/DutchV3Order.ts
- lib/repositories/RelayOrderRepository.ts
- lib/repositories/base.ts
- lib/repositories/dutch-orders-repository.ts
- lib/repositories/generic-orders-repository.ts
- lib/repositories/limit-orders-repository.ts
- swagger.json
- test/integ/repositories/dynamo-repository.test.ts
- test/integ/repositories/limit-orders-repository.test.ts
- test/unit/models/DutchV3Order.test.ts
- Add `fillBlock` as one of the fields in an order's status
- Make this field show up in queries for DutchV3 orders
> feat: add fillBlock to table & V3 queries

- package.json
- yarn.lock
Old version was missing Permit2 address for chain 130
> Bump SDK version

- lib/handlers/get-unimind/handler.ts
- lib/handlers/get-unimind/schema/index.ts
- lib/util/constants.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- Add flag for orders that don't require parameters returned (only seeking to have quote metadata posted)
- Use default values when it's a newly seen pair & append to unimind table
- Tests
> feat, test: flag for only posting metadata; default value support

- lib/handlers/get-unimind/schema/index.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- Case-sensitive acceptance of logOnly
- Non-booleans are not accepted
- Tests
> feat, test: enforce strict logOnly parameters

- lib/handlers/get-unimind/handler.ts
- lib/handlers/get-unimind/schema/index.ts
- lib/repositories/quote-metadata-repository.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- When hitting Unimind endpoint with quote metadata, the route field will be optional
> feat, test: allow route in metadata to be optional

- bin/stacks/cron-stack.ts
- bin/stacks/step-function-stack.ts
- lib/crons/gs-reaper.ts
- lib/util/constants.ts
- test/unit/handlers/gs-reaper/gs-reaper.test.ts
The cron job approach was too slow and hit AWS' 15 min limit. Migrating to the feature to a step function so it can run much longer.
1. **GET_OPEN_ORDERS**: Retrieves and parses open orders from the database
2. **PROCESS_BLOCKS**: Scans blocks for order fill events across configured block ranges for each supported order type
3. **CHECK_CANCELLED**: Validates unfilled orders for cancellations and expirations
4. **UPDATE_DB**: Persists status changes and handles chain transitions
This is the step function state machine:
Each `ContinueExecution` it will pick up on the stage that it left off, passing the result from the previous call.
> Migrate Reaper to a step function

- bin/stacks/step-function-stack.ts
- lib/crons/gs-reaper.ts
- test/unit/handlers/gs-reaper/gs-reaper.test.ts
Only process up to 50 orders at once. Remove an order from `parsedOrders` list if it's added to the `orderUpdates` list.
Run the job every 5 hours.
> Limit reaper step function data size

- bin/stacks/step-function-stack.ts
The reaper currently dies after 15 to 25 minutes and I believe it's due to timeout. Also increasing memory capacity to see if it helps.
> Increase reaper timeout and memory

- bin/config.ts
- bin/stacks/dynamo-stack.ts
- jest-dynamodb-config.js
- lib/config/dynamodb.ts
- lib/crons/unimind-algorithm.ts
- lib/entities/RelayOrderEntity.ts
- lib/handlers/get-orders/schema/index.ts
- lib/handlers/shared/get.ts
- lib/models/RelayOrder.ts
- lib/repositories/IndexMappers/OffchainOrderIndexMapper.ts
- lib/repositories/dutch-orders-repository.ts
- lib/repositories/generic-orders-repository.ts
- lib/repositories/limit-orders-repository.ts
- lib/repositories/util.ts
- test/integ/crons/unimind-algorithm.test.ts
- test/integ/repositories/dynamo-repository.test.ts
- test/integ/repositories/limit-orders-repository.test.ts
- test/unit/builders/QueryParamsBuilder.ts
- test/unit/handlers/get-orders.test.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- test/unit/handlers/post-order/post-order.test.ts
- test/unit/repositories/OffchainOrderIndexMapper.test.ts
- test/unit/repositories/quote-metadata-repository.test.ts
- test/unit/repositories/unimind-parameters-repository.test.ts
Unimind update algorithm needs to perform queries on `pair` in the `Orders` table
1. Adds `pair` as a GSI to enable queries on the `pair` attribute
2. Updates the `get-orders` endpoint to utilize this GSI to allow API users to also query for orders based on `pair`
> feat, test: add pair as a GSI in Orders table

- lib/crons/unimind-algorithm.ts
- lib/handlers/get-unimind/handler.ts
- lib/util/unimind.ts
- test/integ/crons/unimind-algorithm.test.ts
- Turn the address filter into a function so further updates apply to all cases the filter is used
- Enable the Unimind cron to use the address filter
> feat, test: unimind address filter function; filter on cron

- lib/util/field-validator.ts
- The field validator is declaring top-of-module env variables before they're fully loaded
- Lazy load it with a function so it's only accessed when used
> feat: lazy load env vars for field validator

- lib/entities/Order.ts
- lib/handlers/get-unimind/handler.ts
- lib/models/DutchV3Order.ts
- lib/repositories/dutch-orders-repository.ts
- lib/repositories/quote-metadata-repository.ts
- lib/services/analytics-service.ts
- test/integ/crons/unimind-algorithm.test.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- test/unit/handlers/post-order/post-order.test.ts
- test/unit/repositories/quote-metadata-repository.test.ts
- test/unit/services/analytics-service.test.ts
Add a `usedUnimind` flag for quotes that were given Unimind parameters
Orders ultimately submitted from those quotes will be recorded and logged with the boolean `usedUnimind`
> feat: usedUnimind flag and analytics

- lib/handlers/get-unimind/handler.ts
- `usedUnimind` is a required field and was not being set in the `logOnly` case
- Add error handling to catch failures to record `quoteMetadata` in the future
> fix: set usedUnimind flag; add error handling

- lib/crons/unimind-algorithm.ts
- lib/unimind/batchedStrategy.ts
- lib/unimind/priceImpactStrategy.ts
- lib/util/unimind.ts
Allows us to use strong types instead of `any`
> Use generics

- lib/services/analytics-service.ts
Log `priceImpact` and `referencePrice` so we can pick it up in BigQuery to see this information among X orders
> feat: log priceImpact, referencePrice for BigQuery

- lib/handlers/get-unimind/handler.ts
- lib/unimind/priceImpactStrategy.ts
- lib/util/constants.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- test/unit/util/unimind-algorithm.test.ts
- Set a ceiling for `tau` for user safety (with test)
- Fix bps unit bug in `f(extrinsic, intrinsic) -> pi, tau`
- Adjust `targetWaitTime` to 8 blocks
- Increase learning rates by 50%
> feat, test: adjust model parameters; fix bps unit bug; tau safety ceiling

- lib/handlers/check-order-status/fill-event-logger.ts
- lib/handlers/check-order-status/service.ts
- lib/handlers/check-order-status/util.ts
- lib/services/analytics-service.ts
- test/unit/handlers/fill-event-logger.test.ts
For DutchV3 orders, we can calculate an exact fill time in units of blocks. Logging it in `FillEventLogger` will propagate it to the Redshift S3 so that we can ingest it into BigQuery to add to our dashboards.
> feat: log fill block for DutchV3 orders

- lib/crons/unimind-algorithm.ts
- lib/models/DutchV3Order.ts
- lib/repositories/IndexMappers/OffchainOrderIndexMapper.ts
- test/integ/crons/unimind-algorithm.test.ts
- test/unit/repositories/OffchainOrderIndexMapper.test.ts
When non-Unimind `Dutch_V3` are posted in the `Orders` table, they do not have `QuoteMetadata` and thus have missing fields. 
One of these missing fields is the `pair` field, which is converted to the string `"undefined"` when fetched by DynamoDB.
Before, we tried to look at the existence of this field to determine if an order used Unimind or not. 
This change intelligently sets the `usedUnimind` variable upon insertion to the `Orders` table based on if `QuoteMetadata` exists. 
This works because Unimind orders have corresponding `QuoteMetadata` entries indexed by their `quoteId`. If `QuoteMetadata` exists, it's still possible for `usedUnimind` to still be set to `false`, which occurs when Unimind decides to assign public parameters (default 15, 15) to the quote. This case is also …
> feat: clean detection of Unimind orders; detailed logging

- bin/stacks/reaper-stack.ts
uniRPC isn't yet able to query events across block ranges due to AWS lambda limitation. Migrating back to QN until it's supported.
> Update to QN

- bin/app.ts
AWS CDK from `2.1017` -> `2.1018` broke the CodeBuild pipeline:
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'aws-cdk@2.1018.0',
npm WARN EBADENGINE   required: { node: '>= 18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.20.2', npm: '8.19.4' }
npm WARN EBADENGINE }
```
The default CodeBuild config seems to still use Node 16, which we should override
> feat: specify node version in CodeBuild

- lib/crons/unimind-algorithm.ts
After the price impact calculation fixes, sometimes price impact can be equal to 0
This would short-circuit a check that was intended to see if the field was accessible
> fix: allow 0 priceImpact

- lib/crons/gs-reaper/gs-reaper.ts
- lib/util/constants.ts
- test/unit/handlers/gs-reaper/gs-reaper.test.ts
Now that we've processed through the backlog of incorrectly labeled orders, we can decrease the lookback and reintroduce all chains/order-types.
- Lookback of 1 week
- We still have a lot of open limit orders so if it takes multiple days to go through all orders, we want to make sure we don't miss any updates.
- Re-adds dutchReaper and non-Mainnet chains
Since each reaper instance keeps track of the current order query `cursor` by chain, the flow will look something like this:
1. DutchReaper
a.  Process 1000 orders for Mainnet
b.  Process 1000 orders for Arbitrum
c.  Process 1000 orders for Base
d.  Process 1000 orders for Unichain
2. LimitOrder
a.  Process 1000 orders for Mainnet
3. DutchReaper
a.  Process _the next_ 1000 orders for Mainnet
b.  Process _the next_ 1000 orders for Arbitrum …
> feat(Reaper): Re-add all order types

- bin/stacks/api-stack.ts
- bin/stacks/dashboard-stack.ts
- lib/handlers/get-unimind/handler.ts
- Fix typo in the requests/responses panel
- Add panel for the % of the Unimind orders that are suggested an auction start price lower than the AMM
- Add panel for the percentiles of pi values
- Add panel for the histogram of pi values (bucketed by 1bps)
> feat: add dashboard panel for proportion of Unimind orders with negative pi parameter

- lib/handlers/get-unimind/handler.ts
- lib/unimind/priceImpactStrategy.ts
- lib/util/constants.ts
- test/unit/handlers/get-unimind/get-unimind.test.ts
- test/unit/util/unimind-algorithm.test.ts
1. Add guardrail to prevent negative Lambda2 from being used
2. Add guardrail to prevent large price impacts from feeding into Unimind (>2% price impact)
3. Further fine-tune learning rates as part of the binary search
4. Bump algorithm version to get negative Lambda2 pairs unstuck
> feat, test: add Unimind computation guardrails; fine-tune learning rates

- bin/stacks/api-stack.ts
default evaluation window is 5 mins, so old rate limit is effectively 3 RPS which is a little too low given that we added more chains, and that chains now have sub-second block time
> chore: double get-orders rate limit

- jest-dynamodb-config.js
- lib/crons/gs-reaper/gs-reaper.ts
- lib/handlers/check-order-status/service.ts
- lib/util/Permit2Validator.ts
- package.json
- test/integ/handlers/check-order-status.test.ts
- test/unit/handlers/gs-reaper/gs-reaper.test.ts
- test/unit/util/Permit2Validator.test.ts
- yarn.lock
We can't use the default quoter for permissioned tokens since the input tokens cannot be transferred and fails with insufficient-token. Therefore, we should skip the quoter for permissioned tokens and use a new Permit2Validator which only checks if the nonce is used (cancelled) or expired.
The fill event tracker will pick up filled orders.
This is used in the async order status checkers: `check-order-status` and `gs-reaper`.
> fix(reaper + check-order-status): Permissioned token status check

- lib/handlers/order-notification/handler.ts
- lib/handlers/order-notification/types.ts
- lib/handlers/post-order/index.ts
- lib/providers/base.ts
- lib/providers/json-webhook-provider.ts
- lib/providers/s3-webhook-provider.ts
- lib/services/UniswapXOrderService.ts
- lib/util/address.ts
- test/unit/handlers/order-notification.test.ts
- test/unit/providers/json-webhook-provider.test.ts
- test/unit/providers/s3-webhook-provider.test.ts
- test/unit/util/address.test.ts
Re-introducing commit `401eb5e63a04166856cf52b5309abb16f54b67bf`.
It appears that spike of errors we saw was due to the deployment rollout and not this particular change.
> feat, test: immediately notify exclusive filler (#595)

- lib/handlers/check-order-status/handler.ts
- lib/handlers/check-order-status/injector.ts
- lib/handlers/check-order-status/service.ts
- lib/handlers/shared/sfn.ts
- lib/services/UniswapXOrderService.ts
- test/unit/handlers/post-order/post-limit-order.test.ts
- test/unit/services/RelayOrderService.test.ts
- test/unit/services/UniswapXOrderService.test.ts
Currently the name of the sfn is postfixed with the `retryCount` which always ends at 301, resulting in naming conflicts. This PR updates the name to be an ever-incrementing index that is unique per sfn instance.
> Update sfn naming to prevent conflicts
